name: Deploy to Namecheap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          # These secrets need to be added in GitHub repository settings
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

      - name: Deploy to Namecheap
        uses: appleboy/scp-action@v0.1.7
        with:
          # SSH connection details
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".next,public,package.json,package-lock.json,next.config.js,.env,.htaccess,index.php"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 0

      - name: Install dependencies on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          # SSH connection details
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            npm ci --production
            chmod -R 755 .
            find . -type f -exec chmod 644 {} \;
            find . -type f -name "*.php" -exec chmod 644 {} \; 